# Generated by Django 3.2 on 2021-05-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee2',
        ),
    ]
