# Generated by Django 3.2 on 2021-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_materialrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='sent_to_all_suppliers',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
