# Generated by Django 3.2 on 2021-05-11 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0005_alter_materialrequest_sent_to_all_suppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials_materialrequest_created_by', to='auth.user'),
            preserve_default=False,
        ),
    ]
