# Generated by Django 3.2 on 2021-05-11 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0007_supplierquotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='quote_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_materialrequest_quote_selected', to='materials.supplierquotation'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierquotation',
            unique_together={('material_request', 'created_by')},
        ),
    ]
